---
- name: Install WireGuard
  apt:
    name: wireguard
    state: present
  become: true

- name: Create WireGuard folder
  shell: mkdir -p /etc/wireguard/
  failed_when: false 
  
- name: Find all hosts with wireguard_public_key
  set_fact:
    vpn_peers: []
    master: []


- name: Collect wireguard agents
  set_fact:
    vpn_peers: "{{ vpn_peers + [item] }}"
  when: 
    - hostvars[item]['wireguard_public_key'] is defined
    - item != inventory_hostname
  loop: "{{ groups['agents'] }}"



- name: Collect WireGuard peers (all masters except myself)
  set_fact:
    master: "{{ master + [item] }}"
  when:
    - item.value.wireguard_public_key is defined
    - item.key != inventory_hostname
  loop: "{{ master_nodes | dict2items }}"

- name: Show contents of vpn_peers
  debug:
    msg:  "{{ vpn_peers }}"

- name: Show contents of vpn_master
  debug:
    msg:  "{{ master }}"

- name: Create WireGuard server configuration file
  template:
    src: server.conf.j2
    dest: /etc/wireguard/{{ master_nodes[inventory_hostname].wireguard_interface }}.conf


- name: enable and persist ip forwarding
  ansible.posix.sysctl: 
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    sysctl_set: yes
    reload: yes

- name: Activate Wireguard at boot
  command: "{{ item }}"
  loop:
    - systemctl enable wg-quick@{{ master_nodes[inventory_hostname].wireguard_interface }}.service
    - systemctl daemon-reload      

- name: Include post-installation tasks
  include_tasks: post_install.yml