---
- name: Reload WireGuard 
  block:
    - command: wg-quick  {{ item }} {{ master_nodes[inventory_hostname].wireguard_interface  }} 
      with_items:
        - down
        - up
      failed_when: false
