apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volumes.pv.name }}
  labels:
    type: local
spec:
  storageClassName: {{ .Values.volumes.storageClassName | default "manual" }}
  capacity:
    storage: {{ .Values.volumes.capacity | default "15Gi" }}
  accessModes: {{ .Values.volumes.pv.accessModes }}
  hostPath:
    path: {{ .Values.volumes.hostPath | default "/data/registry" }}