apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/instance: {{ .Values.appName }}
    app.kubernetes.io/part-of: {{ .Values.appName }}
spec: 
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.appName }}
    spec:
      containers:
        - name: cowrie
          image: {{ .Values.containers.cowrie.image }}
          imagePullPolicy: {{ .Values.containers.cowrie.imagePullPolicy }}
          securityContext:
            runAsUser: 999
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
          ports:
            - name: {{ .Values.service.ports.sshPort.name }}
              containerPort: {{ .Values.service.ports.sshPort.port }}
            - name: {{ .Values.service.ports.telnetPort.name }}
              containerPort: {{ .Values.service.ports.telnetPort.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.ports.sshPort.name }}
            initialDelaySeconds: 5
            periodSeconds: 60
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.ports.sshPort.name }}
            initialDelaySeconds: 15
            periodSeconds: 60
        - name: tcpdump
          securityContext:
            privileged: true
          image: {{ .Values.containers.tcpdump.image }}
          imagePullPolicy: {{ .Values.containers.tcpdump.imagePullPolicy }}
          command: {{ .Values.containers.tcpdump.command | toJson }}
          args:
            - "tcpdump -i {{ .Values.containers.tcpdump.interface }} -nn -tt '{{ .Values.containers.tcpdump.filter }}' -G {{ .Values.containers.tcpdump.rotate_seconds }} -w {{ .Values.containers.tcpdump.outputPath }}"
          volumeMounts:
            - mountPath: {{ .Values.containers.tcpdump.monthPath }}
              name: {{ .Values.volumes.pv.name }}
      volumes:
        - name: {{ .Values.volumes.pv.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.pvc.name }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values: 
                    {{ - range .Values.nodeAffinity.hostname.values }}
                        - {{ . }}
                    {{- end }}




