apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tcpdump-cowrie
  namespace: hpot
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi   

