apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/instance: {{ .Values.appName }}
    app.kubernetes.io/part-of: {{ .Values.appName }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.appName }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
  externalIPs:
    {{- range .Values.service.externalIPs }}
    - {{ . }}
    {{- end }}
