---
# https://dev.to/tangramvision/exploring-ansible-via-setting-up-a-wireguard-vpn-3389
- name: Install WireGuard
  apt:
    name: wireguard
    state: present
  become: true

- name: Create WireGuard folder
  shell: mkdir /etc/wireguard/
  failed_when: false 

- name: Create WireGuard server configuration file
  template:
    src: server.conf.j2
    dest: /etc/wireguard/{{ wireguard_interface }}.conf
  become: true

- name: enable and persist ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    sysctl_set: yes
    reload: yes

- name: Activate Wireguard at boot
  command: "{{ item }}"
  loop:
    - systemctl enable wg-quick@{{ wireguard_interface }}.service
    - systemctl daemon-reload      

- name: Include post-installation tasks
  include_tasks: post_install.yml