- name: Debug variables for application
  debug:
    msg:
      - "Application: {{ application }}"
      - "Group vars loaded: {{ application_vars | default({}) | length > 0 }}"
      - "host_specific defined: {{ application_vars.host_specific is defined }}"

- name: Deploy Helm chart for Darknet in each required node
  command: >
    {% set host_specific = application_vars.host_specific | default({}) %}
    {% set namespace = application_vars.darknet_namespace | default(application) %}  
    {% set host_config = host_specific[item] | default({}) %}
    {% set darknet_range = host_config.darknet_range | default('0.0.0.0/0') %}
    {% set exclude_ips = host_config.darknet_exclude_ips | default([]) %}
    {% set tcpdump_interface = host_config.tcpdump_interface | default('eth0') %}
    {% set server_ip = [] %}
    {% for ip in exclude_ips %}
      {% set _ = server_ip.append("host " + ip) %}
    {% endfor %}
    {% set filter_condition = "ip and (net " ~ darknet_range ~ ")" %}
    {% if server_ip %}
      {% set filter_condition = filter_condition ~ " and not (" ~ server_ip | join(' or ') ~ ")" %}
    {% endif %}
    {% set tcpdump_rotate_seconds = application_vars.tcpdump_rotate_seconds | default(3600) %}
    {% set darknet_mountPath = application_vars.darknet_mountPath | default('/data/darknet') %}
    {% set tcpdump_file_pattern = application_vars.tcpdump_file_pattern | default('capture-%Y%m%d-%H%M%S.pcap') %}
    {% set darknet_hostPath = application_vars.darknet_hostPath | default('/data/darknet') %}

    helm upgrade -i {{ application }}-{{ item }} {{ playbook_dir }}/../resources/helm-charts/{{ application }} 
    --namespace {{ namespace }} 
    --create-namespace
    --set name={{ application }}-{{ item }}
    --set appName={{ application }}-{{ item }}
    --set namespace={{ namespace }}
    --set volumes.pv.name={{ application }}-pv-{{ item }}
    --set volumes.pvc.name={{ application }}-pvc-{{ item }}
    --set containers.tcpdump.interface="{{ tcpdump_interface }}"
    --set containers.tcpdump.filter="{{ filter_condition }}"
    --set containers.tcpdump.rotate_seconds="{{ tcpdump_rotate_seconds }}"
    --set containers.tcpdump.outputPath="{{ darknet_mountPath }}/{{ tcpdump_file_pattern }}"
    --set containers.tcpdump.mountPath="{{ darknet_mountPath }}"
    --set volumes.pvc.hostPath.path="{{ darknet_hostPath }}"       
    --set nodeAffinity.hostname.values[0]="{{ item }}"
  register: helm_result
  with_items: "{{ groups[application] }}"