apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.pvc.name }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.volumes.pvc.storageClassName }}
  accessModes:
    {{- range .Values.volumes.pvc.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.volumes.pvc.resources.requests.storage }}