{{- range $nodeName, $nodeConfig := .Values.captureNodes }}
{{- if and $nodeConfig.enabled $nodeConfig.arp.enabled }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "darknet.fullname" $ }}-arp-{{ $nodeName }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "darknet.arp.labels" $ | nindent 4 }}
    darknet.io/node: {{ $nodeName }}
spec:
  selector:
    matchLabels:
      {{- include "darknet.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: arp
      darknet.io/node: {{ $nodeName }}
  template:
    metadata:
      labels:
        {{- include "darknet.arp.labels" $ | nindent 8 }}
        darknet.io/node: {{ $nodeName }}
    spec:
      hostNetwork: {{ $.Values.network.hostNetwork }}
      dnsPolicy: {{ $.Values.network.dnsPolicy }}
      
      nodeSelector:
        kubernetes.io/hostname: {{ $nodeName }}
      
      containers:
      {{- if $nodeConfig.arp.ipv4.enabled }}
      - name: arp4
        image: "{{ $.Values.arpImages.ipv4.repository }}:{{ $.Values.arpImages.ipv4.tag }}"
        imagePullPolicy: IfNotPresent
        
        securityContext:
          {{- toYaml $.Values.securityContext | nindent 10 }}
        
        env:
        - name: NODE_NAME
          value: {{ $nodeName }}
        
        command: ["/usr/src/arpd/farpd2", "-d", "-i"]
        
        resources:
          {{- toYaml $.Values.resources.arp | nindent 10 }}
      {{- end }}
      
      restartPolicy: Always
{{- end }}
{{- end }}