---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/instance: {{ .Values.appName }}
    app.kubernetes.io/part-of: {{ .Values.appName }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.appName }}
  type: {{ .Values.service.type }}
  ports:
    - name: https
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5000
      nodePort: {{ .Values.service.nodePort }}