    - name: Check if K3s is already installed
      command : k3s
      register: result
        #Installed rc==0, not installed rc ==2
      changed_when: false   
      failed_when: false

    - name: Install and configure K3s
      block:
        - name: Download K3s
          get_url:
            url: "https://get.k3s.io"
            dest: "/tmp/install_k3s.sh"
            mode: '0755'
      
        - name: Run K3s installer script
          command: "/tmp/install_k3s.sh"
          environment:
                K3S_NODE_NAME: "{{ansible_hostname}}"
                K3S_URL: https://50.0.0.1:6443 
                K3S_TOKEN : "{{hostvars['node1'].k3s_token}}"
         
      #when: result.rc != 0
   
    - name: "Edit K3s service "
      copy:
        dest: "/etc/systemd/system/k3s-agent.service"
        content: |  
            [Unit]
            Description=Lightweight Kubernetes
            Documentation=https://k3s.io
            Wants=network-online.target
            After=network-online.target

            [Install]
            WantedBy=multi-user.target

            [Service]
            Type=notify
            EnvironmentFile=-/etc/default/%N
            EnvironmentFile=-/etc/sysconfig/%N
            EnvironmentFile=-/etc/systemd/system/k3s-agent.service.env
            KillMode=process
            Delegate=yes
            # Having non-zero Limit*s causes performance problems due to accounting overhead
            # in the kernel. We recommend using cgroups to do container-local accounting.
            LimitNOFILE=1048576
            LimitNPROC=infinity
            LimitCORE=infinity
            TasksMax=infinity
            TimeoutStartSec=0
            Restart=always
            RestartSec=5s
            ExecStartPre=/bin/sh -xc '! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service 2>/dev/null'
            ExecStartPre=-/sbin/modprobe br_netfilter
            ExecStartPre=-/sbin/modprobe overlay
            ExecStart=/usr/local/bin/k3s \
                agent \
            ExecStart=/usr/local/bin/k3s agent --node-ip {{hostvars[ ansible_hostname ].ip_vpn}} --flannel-iface=wg0

    - name: Reload systemd and restart K3S service
      systemd:
          daemon_reload: yes
          name: k3s-agent
          enabled: yes
          state: restarted 


#curl -sfL https://get.k3s.io | K3S_URL=https://10.0.0.1:6443 K3S_TOKEN=K1047421038c1a6b28861b8d4ac1e001f0ce65c8201606732dc444c47c837c3864f::server:ca4392a1e9d257daeaf4ab0d57237226 K3S_NODE_NAME=name-node sh - 
