apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: client
          image: {{ .Values.containers.client.image }}
          imagePullPolicy: {{ .Values.containers.client.imagePullPolicy }}
          args: {{ toYaml .Values.containers.client.args | nindent 12 }}
          ports:
          - containerPort: {{ .Values.containers.client.port }}
          volumeMounts:
            {{- range .Values.containers.client.volumeMounts }}
            - mountPath: {{ .mountPath }}
              name: {{ .name }}
            {{- end }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values: 
                    {{- range .Values.nodeAffinity.hostname.values }}
                    - {{ . }}
                    {{- end }}
      volumes:
        {{- range .Values.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .claimName }}
        {{- end }}

