global:
  namespace: l4responder
  storageClass: manual

l4responder_server:
  labels:
     app: l4responder-server
  terminationGracePeriodSeconds: 0
  container:
    name: responder
    image:
      repository: registry.local:5000/public/l4responder_server 
      tag: latest
      pullPolicy: Always
    containerPort: 60000
    hostPort: 60000 
