global:
  namespace: l4responder
  storageClass: local-path

# Image tag — overridden at deploy time with git SHA
image_tag: latest

networkPolicy:
  enabled: true

container_port: 30000
host_port: 30000

l4responder_server:
  labels:
     app: l4responder
  terminationGracePeriodSeconds: 0
  container:
    name: responder
    image:
      repository: registry.local:5000/public/l4responder_server
      pullPolicy: IfNotPresent
