deploymentName: darknet
appName: darknet
hostNetwork: true
namespace: darknet

containers:
  tcpdump:
    image: nicolaka/netshoot
    imagePullPolicy: IfNotPresent
    mountPath: /data/darknet
    command:
      - "/bin/bash"
      - "-c"
    interface: eth0
    rotate_seconds: 3600
    filter: "ip and (net 10.10.0.0/24)"
    outputPath: "/data/darknet/trace-%Y%m%d_%H-%M-%S_%s.pcap"

nodeAffinity:
  hostname:
    values:
      - poli-worker-00

volumes:
  pv:
    name: pv-volume-tcpdump-darknet
    storageClassName: manual
    capacity: 5Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: "/data/darknet"
  pvc:
    name: pvc-tcpdump-darknet
    storageClassName: manual
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
