- name: Deploy Helm chart for Cowrie with TCPDump in each required node
  command: >
    {% set listening_ips = hostvars[item].darknet_exclude_ips %}
    {% set filter_ips = [] %}
    {% for ip in listening_ips %}
      {% set _ = filter_ips.append("host " + ip) %}
    {% endfor %}

    helm upgrade -i cowrie-ansible-{{ item }} {{ playbook_dir }}/resources/helm-charts/cowrie --namespace {{ hostvars[item].namespace }} --create-namespace
    --set name=cowrie-{{ item }}
    --set appName=cowrie-{{ item }}
    --set namespace={{ hostvars[item].namespace }}
    --set volumes.pv.name=cowrie-pv-{{ item }}
    --set volumes.pvc.name=cowrie-pvc-{{ item }}
    --set containers.tcpdump.filter="(port {{ hostvars[item].sshPort.port }} or port {{ hostvars[item].telnetPort.port }}) and ( {{ filter_ips | join(' or ')  }} )"
    --set containers.tcpdump.rotate_seconds="{{ hostvars[item].tcpdump_rotate_seconds }}"
    --set containers.tcpdump.outputPath="{{hostvars[item].mountPath}}/{{ hostvars[item].tcpdump_file_pattern }}"
    --set containers.tcpdump.mountPath="{{hostvars[item].mountPath}}"
    --set volumes.pvc.hostPath.path="{{ hostvars[item].hostPath }}"
    --set nodeAffinity.hostname.values[0]="{{ item }}"
  environment:
    KUBECONFIG: "{{ fetch_result.dest }}"
  with_items: "{{ groups['cowrie'] }}"
