{{- range $nodeName, $nodeConfig := .Values.toolbox.workers }}
{{- if $nodeConfig.enabled }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: toolbox-{{ $nodeName }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $.Values.toolbox.labels.app }}
    l4respondertoolbox.io/node: {{ $nodeName }}
spec:
 
  selector:
    matchLabels:
      app: {{ $.Values.toolbox.labels.app }}
      l4respondertoolbox.io/node: {{ $nodeName }}
  template:
    metadata:
      labels:
        app: {{ $.Values.toolbox.labels.app }}
        l4respondertoolbox.io/node: {{ $nodeName }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ $nodeName }}
      serviceAccountName: {{ $.Values.toolbox.serviceAccount.name }}
      hostNetwork: {{ $.Values.toolbox.network.hostNetwork }}
      containers:
        - name: {{ $.Values.toolbox.container.name }}
          image: "{{ $.Values.toolbox.container.image.repository }}:{{ $.Values.toolbox.container.image.tag }}"
          imagePullPolicy: {{ $.Values.toolbox.container.image.pullPolicy }}
          securityContext:
            privileged: {{ $.Values.toolbox.securityContext.privileged }}
          env:
            ## TODO: load these from values.yaml of the respective deployments

            - name: L4_SERVER_APP_NAME
              value: "{{ $.Values.toolbox.l4responder.labels.app }}" 
            - name: DARKNET_APP_NAME
              value: "{{ $.Values.toolbox.darknet.labels.app }}" 


            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CONTAINER_PORT
              value: "{{ $.Values.toolbox.l4responder.container.hostPort }}"

              {{- range $index, $ip := $nodeConfig.l4responder.ipRanges }}
            - name: IP_RANGE_{{ $index }}
              value: "{{ $ip.network }}"
              {{- end }}
             
              {{- range $index, $range := $nodeConfig.l4responder.portRanges }}
            - name: PORT_RANGE_{{ $index }}
              value: "{{ $range.start }}-{{ $range.end }}"
              {{- end }}
            
{{- end }}
{{- end }}