{{- range $nodeName, $nodeConfig := .Values.workers }}
{{- if $nodeConfig.enabled }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: toolbox-{{ $nodeName }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $.Values.toolbox.labels.app }}
    l4respondertoolbox.io/node: {{ $nodeName }}
spec:
 
  selector:
    matchLabels:
      app: {{ $.Values.toolbox.labels.app }}
      l4respondertoolbox.io/node: {{ $nodeName }}
  template:
    metadata:
      labels:
        app: {{ $.Values.toolbox.labels.app }}
        l4respondertoolbox.io/node: {{ $nodeName }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ $nodeName }}
      serviceAccountName: {{ $.Values.toolbox.serviceAccount.name }}
      hostNetwork: {{ $.Values.toolbox.network.hostNetwork }}
      containers:
        - name: {{ $.Values.toolbox.container.name }}
          image: "{{ $.Values.toolbox.container.image.repository }}:{{ $.Values.toolbox.container.image.tag }}"
          imagePullPolicy: {{ $.Values.toolbox.container.image.pullPolicy }}

          securityContext:
            privileged: {{ $.Values.toolbox.securityContext.privileged }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          {{- $l4w := index $.Values.extra_app_configs.l4responder.values.workers $nodeName }}
          {{- if $l4w.enabled }}
    

            - name: L4_SERVER_APP_NAME
              value: "{{ $.Values.extra_app_configs.l4responder.app }}"
            - name: CONTAINER_PORT_RESPONDER
              value: "{{ $.Values.extra_app_configs.l4responder.values.host_port }}"
     
          {{- range $index, $ip := $l4w.ipRanges }}
            - name: IP_RANGE_RESPONDER_{{ $index }}
              value: "{{ $ip.network }}"
          {{- end }}
          {{- range $index, $range := $l4w.portRanges }}
            - name: PORT_RANGE_RESPONDER_{{ $index }}
              value: "{{ $range.start }}-{{ $range.end }}"
              {{- end }}
          {{- end }}
       

             
{{- end }}
{{- end }}