apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.appName }}-network-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.appName }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    {{- range .Values.networkPolicy.allowedCidrs }}
    - ipBlock:
        cidr: {{ . }}
    {{- end }}
    ports:
    - protocol: TCP
      port: {{ .Values.service.port }}