{{- range $key, $value := .Values.pv }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $value.name }}-{{$.Values.appName}}
  namespace: {{ $.Values.namespace }}
  labels:
    type: local
spec:
  storageClassName: {{ $value.storageClassName }}
  capacity:
    storage: {{ $value.capacity }}
  accessModes:
    {{- range $value.accessModes }}
    - {{ . }}
    {{- end }}
  hostPath:
    path: {{ $value.hostPath.path }}
---
{{- end }}