{{- range $nodeName, $nodeConfig := .Values.udpResponderNodes }}
{{- if $nodeConfig.enabled }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "udpresponder.fullname" $ }}-{{ $nodeName }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: udp-responder
    udp-responder.io/node: {{ $nodeName }}
spec:
  selector:
    matchLabels:
      app: udp-responder
      udp-responder.io/node: {{ $nodeName }}
  template:
    metadata:
      labels:
        app: udp-responder
        udp-responder.io/node: {{ $nodeName }}
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: {{ $nodeConfig.nodeSelector }}
      containers:
        - name: udp-responder
          image: "{{ $.Values.containers.udpresponder.repository }}:{{ $.Values.containers.udpresponder.tag | default "latest" }}"
          imagePullPolicy: {{ $.Values.containers.udpresponder.pullPolicy }}
          args:
             - --interface 
             - {{ $nodeConfig.config.interface | quote }}
             - --subnet
             - {{ $nodeConfig.config.subnet | quote }}
             - --protocols
             - {{ $nodeConfig.config.protocols | quote }}
{{- end }}
{{- end }}
