apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowrie-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cowrie-1
  template:
    metadata:
      labels:
        app: cowrie-1
    spec:
      volumes:
      - name: cowrie-data
        persistentVolumeClaim:
          claimName: cowrie-pvc-1
      containers:
      - name: cowrie
        image: cowrie/cowrie:latest
        volumeMounts:
        - name: cowrie-data
          mountPath: "/cowrie/cowrie-git/var/log/cowrie"
      nodeName: server1