#!/bin/bash

# Default values
DEFAULT_WG_IP="10.0.0.1"
DEFAULT_IFACE="enp0s3"
DEFAULT_LISTEN_PORT="51820"

# Function to display help message
show_help() {
    echo "Usage: $0 [WG_IP] [iface] [ListenPort]"
    echo "  WG_IP        The IP address of this host in the WireGuard tunnels (default: $DEFAULT_WG_IP)"
    echo "  iface        The internet interface (default: $DEFAULT_IFACE)"
    echo "  ListenPort   The UDP port on which WireGuard will listen (default: $DEFAULT_LISTEN_PORT)"
    echo "  --help       Display this help message and exit"
}

# Check if the --help option is provided
if [[ "$1" == "--help" ]]; then
    show_help
    exit 0
fi

# Command line arguments with defaults
WG_IP="${1:-$DEFAULT_WG_IP}"
iface="${2:-$DEFAULT_IFACE}"
ListenPort="${3:-$DEFAULT_LISTEN_PORT}"

# Install WireGuard
sudo apt-get install -y wireguard

# Generate WireGuard keys
wg genkey | tee privatekey | wg pubkey > publickey

# Create WireGuard configuration file
sudo bash -c "cat > /etc/wireguard/wg0.conf << EOF
[Interface]

# The IP address of this host in the WireGuard tunnels
Address = $WG_IP

# The UDP port on which WireGuard will listen
ListenPort = $ListenPort

# Set the private key to the value of the privatekey file generated by the previous command
PrivateKey = $(cat privatekey)

# Commands to run after the interface is up
PostUp   = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o $iface -j MASQUERADE

# Commands to run after the interface is down
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o $iface -j MASQUERADE
EOF"

# Create WireGuard Up service file
sudo bash -c "cat > /etc/systemd/system/wireguard-up.service << EOF
[Unit]
Description=WireGuard Up Service
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/wg-quick up wg0

[Install]
WantedBy=default.target
EOF"

# Reload systemd and start WireGuard service
sudo systemctl daemon-reload
sudo systemctl enable wireguard-up.service
sudo systemctl start wireguard-up.service

# Install K3s with WireGuard
curl -sfL https://get.k3s.io | K3S_NODE_NAME=master1 sh - 

# Check for an empty line and remove it before appending the echo message
sed -i '/^$/d' /etc/systemd/system/k3s.service

# Configure flannel in node
echo "ExecStart=/usr/local/bin/k3s server --advertise-address $WG_IP --flannel-iface=wg0" | sudo tee -a /etc/systemd/system/k3s.service

# Restart k3s service
sudo systemctl daemon-reload 
sudo systemctl restart k3s.service
