all:
  hosts:
    master-00:
      ansible_host: 10.10.0.100
      ansible_user: vagrant
      ansible_ssh_private_key_file: "../vagrant/.vagrant/machines/master-00/libvirt/private_key"
      wireguard_ip: "10.0.0.100"
      public_interface: "eth0"
            
    worker-00:
      ansible_host: 10.10.0.101
      ansible_user: vagrant
      ansible_ssh_private_key_file: "../vagrant/.vagrant/machines/worker-00/libvirt/private_key"
      wireguard_ip: "10.0.0.101"
      public_interface: "eth0"

    worker-01:
      ansible_host: 10.10.0.102
      ansible_user: vagrant
      ansible_ssh_private_key_file: "../vagrant/.vagrant/machines/worker-01/libvirt/private_key"
      wireguard_ip: "10.0.0.102"
      public_interface: "eth0"

  children:
    deployment:
      hosts:
        localhost:
          ansible_connection: local
    
    registry:
      hosts:
        master-00:
    
    master:
      hosts:
        master-00:
    
    agents:
      hosts:
        worker-00:
        worker-01:
    
    darknet:
      hosts:
        worker-00:    
        worker-01:    
        master-00:
