all:
  hosts:
    master-00:
      ansible_host: 10.10.0.100
      ansible_user: vagrant
      ansible_ssh_private_key_file: "../vagrant/.vagrant/machines/master-00/libvirt/private_key"
      wireguard_ip: "10.0.0.100"
      public_interface: "eth0"
   # master-01:
    #  ansible_host: 10.10.0.103
   #   ansible_user: vagrant
   #  ansible_ssh_private_key_file: "../vagrant/.vagrant/machines/master-01/libvirt/private_key"
   #   wireguard_ip: "10.0.0.103"
   #   public_interface: "eth0"     
   # master-02:
   #   ansible_host: 10.10.0.104
   #   ansible_user: vagrant
   #   ansible_ssh_private_key_file: "../vagrant/.vagrant/machines/master-02/libvirt/private_key"
   #   wireguard_ip: "10.0.0.104"
   #   public_interface: "eth0"   
    #worker-00:
      #ansible_host: 10.10.0.101
     # ansible_user: vagrant
      #ansible_ssh_private_key_file: "../vagrant/.vagrant/machines/worker-00/libvirt/private_key"
     # wireguard_ip: "10.0.0.101"
      #public_interface: "eth0"
    worker-01:
      ansible_host: 10.10.0.102
      ansible_user: vagrant
      ansible_ssh_private_key_file: "../vagrant/.vagrant/machines/worker-01/libvirt/private_key"
      wireguard_ip: "10.0.0.102"
      public_interface: "eth0"

    # worker-02:
    #   ansible_host: 10.10.0.103
    #   ansible_user: vagrant
    #   ansible_ssh_private_key_file: "../vagrant/.vagrant/machines/worker-02/libvirt/private_key"
    #   wireguard_ip: "10.0.0.103"
    #   public_interface: "eth0"      

  children:
    registry:
      hosts:
        master-00:
    
    master:
      hosts:
        master-00:
       # master-01:
       # master-02:
        
    agents:
      hosts:
        worker-01:
        #worker-01:
        # worker-02:

