- name: Uninstall Helm chart for ARP Responder on each agent node
  command: >
    helm uninstall arp-ansible-{{ item }} --namespace  {{ hostvars[item].namespace }}
  environment:
    KUBECONFIG: "{{ fetch_result.dest }}"
  with_items: "{{ groups['arp_responder'] }}"