- name: Uninstall Helm chart for Flower Client  on each agent node
  command: >
    helm uninstall flower-client-{{ item }} --kubeconfig {{ fetch_result.dest }} --namespace  {{ hostvars[item].flower_namespace }}
  with_items: "{{ groups['flower_client'] }}"
