version: "3"
services:

  # ARP service
  arp4:
    build: ./ipv4
    container_name: darknet-arp4
    hostname: worker-arp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - darknet-net
    command: ["/usr/src/arpd/farpd2", "-d", "-i", "eth0", "10.0.0.0/24"]
   
networks:
  darknet-net:
    driver: bridge