version: "3"

services:
  arp4:
    build: ./ipv4
    network_mode: "host"
    restart: always
    entrypoint: "/usr/src/arpd/farpd2"
    command: "-d -i eth0 10.0.0.0/24" 

  pcap-collector:
    build:
      context: .
      dockerfile: Dockerfile
    image: pcap-collector:latest
    volumes:
      #- ./ssh-key:/etc/ssh-keys:ro
      - ./data:/data/collector
    environment:
      - WORKER_NODES=worker-00 worker-01
      - SOURCE_PATH=/data/darknet
      - SSH_USER=vagrant
      - COLLECTION_INTERVAL=3600
    restart: unless-stopped