---
- name: Undo cluster setup
  hosts: all
  become: true
  tasks:
    - name: Stop WireGuard
      command: wg-quick down {{ wireguard_interface | default('wg0') }}
      register: wg_result
      failed_when: false
      changed_when: wg_result.rc == 0

    - name: Remove WireGuard package
      apt:
        name: wireguard
        state: absent
      failed_when: false

    - name: Remove WireGuard configuration directory
      file:
        path: /etc/wireguard
        state: absent

    - name: Run K3s Uninstall script [server]
      command: k3s-uninstall.sh
      args:
        removes: /usr/local/bin/k3s
      when: "'master' in group_names"

    - name: Run K3s Uninstall script [agent]
      command: k3s-agent-uninstall.sh
      args:
        removes: /usr/local/bin/k3s-agent-uninstall.sh
      when: "'agents' in group_names"

    - name: Remove k3s install script
      file:
        path: /usr/local/bin/k3s-install.sh
        state: absent

    - name: Stop Docker service
      systemd:
        name: docker
        state: stopped
      failed_when: false

    - name: Disable and mask Docker service
      systemd:
        name: docker
        enabled: no
        masked: yes
      failed_when: false

    - name: Remove Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - docker-ee
          - containerd.io
        state: absent
      failed_when: false

    - name: Delete Docker data directory
      file:
        path: /var/lib/docker
        state: absent

    - name: Remove Docker systemd unit file
      file:
        path: /etc/systemd/system/docker.service
        state: absent

    - name: Remove Docker systemd drop-in directory
      file:
        path: /etc/systemd/system/docker.service.d
        state: absent

    - name: Reload systemd to apply changes
      systemd:
        daemon_reload: yes
