---      
- name: Configure agents first to collect WireGuard facts
  hosts: agents
  become: true
  roles:
    - common
    - wireguard-client      

- name: Configure master (WireGuard) with client information
  hosts: master
  become: true
  roles:
    - common
    - wireguard-server
  vars:
    vpn_clients: "{{ groups['agents'] + groups['management'] }}"



- name: Configure master (K3s)
  hosts: master
  become: true
  roles:
    - k3s-server



- name: Configure HAProxy load balancer
  hosts: agents
  become: true
  roles:
    - haproxy
    
- name: Configure agents (K3s)
  hosts: agents
  become: true
  roles:
    - k3s-agent