---
- name: Ensure master group is not empty
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check if master group exists and is not empty
      assert:
        that:
          - groups['master'] is defined
          - groups['master'] | length > 0
        fail_msg: "The 'master' group is empty or not defined in the inventory"

- name: Post-installation steps
  hosts: master
  become: true
  roles:
    - role: k3s-server
      tasks_from: post_install

- name: Configure agents
  hosts: agents
  become: true
  roles:
    - common
    - wireguard-client

- name: Post-installation steps on WireGuard server
  hosts: "{{ groups['master'][0] }}"
  become: true
  roles:
    - role: wireguard-server
      tasks_from: post_install

- name: Configure agents
  hosts: agents
  become: true
  roles:
    - k3s-agent
