---
# ansible-playbook -i inventory/hosts.yml --ask-vault-password playbooks/deploy_applications.yml  --ask-become-pass
#jinja2: trim_blocks:True
- name: Copy and modify file from remote host
  hosts: deployment
  vars:
    ansible_python_interpreter: /usr/bin/python3  
  tasks:
    - name: Fetch Kubeconfig from the remote host
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~/.kube/kubeconfig.yaml
        flat: yes
      delegate_to: "{{ groups['master'][0] }}"
      register: fetch_result

    - name: Change Kubeconfig permissions
      ansible.builtin.file:
        path: "{{ fetch_result.dest }}"
        mode: "go-r"

    - name: Ensure yq is installed on localhost
      become: true
      apt:
        name: yq
        state: present
      run_once: true

    - name: Modify the server URL in the YAML file using yq
      shell: |
        yq -yi '.clusters[0].cluster.server = "https://{{ hostvars[groups['master'][0]]['ansible_host'] }}:6443"' {{ fetch_result.dest }}
      run_once: true

    - name: Ensure Helm is installed
      command: helm version
      register: helm_version
      changed_when: False
      failed_when: "'version' not in helm_version.stdout"

    - name: Add kubernetes-dashboard repository
      ansible.builtin.command:
        cmd: helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
      register: add_repo
      changed_when: "'Kubernetes Dashboard has been added' in add_repo.stdout"
      
    - name: Update helm repositories
      ansible.builtin.command:
        cmd: helm repo update
      when: add_repo is changed

    - name: Set the action for the applications
      set_fact:
        operation: "{{ action | default('install') }}"  # install or remove

    # Step 1: Extract the list of applications to deploy
    - name: Get applications to deploy
      set_fact:
        applications_to_deploy: "{{ deployed_applications }}"

    # Step 2: Deploy or remove applications
    - name: Deploy or remove applications
      include_role:
        name: "{{ application }}"
        tasks_from: "{{ operation }}"
      loop: "{{ applications_to_deploy }}"
      loop_control:
        loop_var: application

    # - name: Deploy Kubernetes Dashboard
    #   kubernetes.core.helm:
    #     name: kubernetes-dashboard
    #     chart_ref: kubernetes-dashboard/kubernetes-dashboard
    #     release_namespace: kubernetes-dashboard
    #     create_namespace: true
    #     state: present
    #   environment:
    #     KUBECONFIG: "{{ fetch_result.dest }}"
