---
# ansible-playbook -i inventory/hosts.yml --ask-vault-password playbooks/deploy_applications.yml  --ask-become-pass
#jinja2: trim_blocks:True
- name: Copy and modify file from remote host
  hosts: deployment
  tasks:
    - name: Fetch Kubeconfig from the remote host
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~/.kube/kubeconfig.yaml
        flat: yes
      delegate_to: "{{ groups['master'][0] }}"
      register: fetch_result

    - name: Change Kubeconfig permissions
      ansible.builtin.file:
        path: "{{ fetch_result.dest }}"
        mode: "go-r"

    - name: Ensure yq is installed on localhost
      become: true
      apt:
        name: yq
        state: present
      run_once: true

    - name: Modify the server URL in the YAML file using yq
      shell: |
        yq -yi '.clusters[0].cluster.server = "https://{{ hostvars[groups['master'][0]]['ansible_host'] }}:6443"' {{ fetch_result.dest }}
      run_once: true

    - name: Ensure Helm is installed
      command: helm version
      register: helm_version
      changed_when: False
      failed_when: "'version' not in helm_version.stdout"

    - name: Add kubernetes-dashboard repository
      ansible.builtin.command:
        cmd: helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
      register: add_repo
      changed_when: "'Kubernetes Dashboard has been added' in add_repo.stdout"
      
    - name: Update helm repositories
      ansible.builtin.command:
        cmd: helm repo update
      when: add_repo is changed

    # - name: Deploy Kubernetes Dashboard
    #   kubernetes.core.helm:
    #     name: kubernetes-dashboard
    #     chart_ref: kubernetes-dashboard/kubernetes-dashboard
    #     release_namespace: kubernetes-dashboard
    #     create_namespace: true
    #     state: present
    #   environment:
    #     KUBECONFIG: "{{ fetch_result.dest }}"

    - name: Deploy Helm chart for ARP Responder in each required node
      command: >
        helm upgrade -i arp-ansible-{{ item }} {{ playbook_dir }}/resources/helm-charts/arp-responder --namespace {{ hostvars[item].namespace }} --create-namespace
        --set name=arp-responder-{{ item }}
        --set appName=arp-responder-{{ item }}
        --set namespace={{ hostvars[item].namespace }}
        --set "containers.arp4.args={"{{ hostvars[item].arp4_interface }}","{{ hostvars[item].arp4_network }}"}"
        --set "containers.arp6.args={"{{hostvars[item].arp6_interface}}"}"
        --set nodeAffinity.hostname.values[0]={{ item }}
      environment:
        KUBECONFIG: "{{ fetch_result.dest }}"
      with_items: "{{ groups['arp_responder'] }}"

    - name: Deploy Helm chart for Darknet TCPDump in each required node
      command: >
        {% set used_listening_ips = hostvars[item].darknet_exclude_ips %}
        {% set server_ip = [] %}
        {% for ip in used_listening_ips %}
          {% set _ = server_ip.append("host " + ip) %}
        {% endfor %}

        helm upgrade -i darknet-ansible-{{ item }} {{ playbook_dir }}/resources/helm-charts/darknet --namespace {{ hostvars[item].namespace }} --create-namespace
        --set name=darknet-{{ item }}
        --set appName=darknet-{{ item }}
        --set namespace={{ hostvars[item].namespace }}
        --set volumes.pv.name=darknet-pv-{{ item }}
        --set volumes.pvc.name=darknet-pvc-{{ item }}
        --set containers.tcpdump.interface="{{ hostvars[item].tcpdump_interface }}"
        --set containers.tcpdump.filter="ip and (net {{ hostvars[item].darknet_range }} and not ( {{ server_ip | join(' or ') }} ))"
        --set containers.tcpdump.rotate_seconds="{{ hostvars[item].tcpdump_rotate_seconds }}"
        --set containers.tcpdump.outputPath="{{hostvars[item].mountPath}}/{{ hostvars[item].tcpdump_file_pattern }}"
        --set containers.tcpdump.mountPath="{{hostvars[item].mountPath}}"
        --set volumes.pvc.hostPath.path="{{ hostvars[item].hostPath }}"       
        --set nodeAffinity.hostname.values[0]="{{ item }}"
      environment:
        KUBECONFIG: "{{ fetch_result.dest }}"
      with_items: "{{ groups['darknet'] }}"

    - name: Deploy Helm chart for Cowrie with TCPDump in each required node
      command: >
        {% set listening_ips = hostvars[item].darknet_exclude_ips %}
        {% set filter_ips = [] %}
        {% for ip in listening_ips %}
          {% set _ = filter_ips.append("host " + ip) %}
        {% endfor %}

        helm upgrade -i cowrie-ansible-{{ item }} {{ playbook_dir }}/resources/helm-charts/cowrie --namespace {{ hostvars[item].namespace }} --create-namespace
        --set name=cowrie-{{ item }}
        --set appName=cowrie-{{ item }}
        --set namespace={{ hostvars[item].namespace }}
        --set volumes.pv.name=cowrie-pv-{{ item }}
        --set volumes.pvc.name=cowrie-pvc-{{ item }}
        --set containers.tcpdump.filter="(port {{ hostvars[item].sshPort.port }} or port {{ hostvars[item].telnetPort.port }}) and ( {{ filter_ips | join(' or ')  }} )"
        --set containers.tcpdump.rotate_seconds="{{ hostvars[item].tcpdump_rotate_seconds }}"
        --set containers.tcpdump.outputPath="{{hostvars[item].mountPath}}/{{ hostvars[item].tcpdump_file_pattern }}"
        --set containers.tcpdump.mountPath="{{hostvars[item].mountPath}}"
        --set volumes.pvc.hostPath.path="{{ hostvars[item].hostPath }}"
        --set nodeAffinity.hostname.values[0]="{{ item }}"
      environment:
        KUBECONFIG: "{{ fetch_result.dest }}"
      with_items: "{{ groups['cowrie'] }}"
