---
# ansible-playbook -i inventory/hosts.yml --ask-vault-password playbooks/deploy_applications.yml  --ask-become-pass
#jinja2: trim_blocks:True
- name: Copy and modify file from remote host
  hosts: deployment
  tasks:
    - name: Fetch Kubeconfig from the remote host
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~/.kube/kubeconfig.yaml
        flat: yes
      delegate_to: "{{ groups['master'][0] }}"
      register: fetch_result

    - name: Change Kubeconfig permissions
      ansible.builtin.file:
        path: "{{ fetch_result.dest }}"
        mode: "go-r"

    - name: Ensure yq is installed on deployment node
      become: true
      apt:
        name: yq
        state: present
      run_once: true

    - name: Modify the server URL in the YAML file using yq
      shell: |
        yq -yi '.clusters[0].cluster.server = "https://{{ hostvars[groups['master'][0]]['ansible_host'] }}:6443"' {{ fetch_result.dest }}
      run_once: true

    - name: Ensure Helm is installed
      command: helm version
      register: helm_version
      changed_when: False
      failed_when: "'version' not in helm_version.stdout"

    - name: Uninstall Helm chart for ARP Responder on each agent node
      command: >
        helm uninstall arp-ansible-{{ item }} --namespace  {{ hostvars[item].namespace }}
      environment:
        KUBECONFIG: "{{ fetch_result.dest }}"
      with_items: "{{ groups['arp_responder'] }}"

    - name: Uninstall Helm chart for Darknet Collector on each agent node
      command: >
        helm uninstall darknet-ansible-{{ item }} --namespace  {{ hostvars[item].namespace }}
      environment:
        KUBECONFIG: "{{ fetch_result.dest }}"
      with_items: "{{ groups['darknet'] }}"

    - name: Uninstall Helm chart for Cowrie honeypot on each agent node
      command: >
        helm uninstall cowrie-ansible-{{ item }} --namespace  {{ hostvars[item].namespace }}
      environment:
        KUBECONFIG: "{{ fetch_result.dest }}"
      with_items: "{{ groups['cowrie'] }}"