---
- name: Undo cluster setup
  hosts: all
  become: true
  tasks:
    - name: Stop WireGuard 
      command: wg-quick  down wg0 
      failed_when: false
      
    - name: Remove previous installation of Wireguard
      shell: apt remove -y wireguard
      failed_when: false
      
    - name: Remove wg0.conf file - if exist
      shell: rm /etc/wireguard/ -r
      failed_when: false

    - name: Run K3s Uninstall script [server]
      when: "'master' in group_names"
      ansible.builtin.command:
        cmd: k3s-uninstall.sh
        removes: /var/lib/rancher/k3s/*

    - name: Run K3s Uninstall script [agent]
      when: "'agent' in group_names"
      ansible.builtin.command:
        cmd: k3s-agent-uninstall.sh
        removes: /var/lib/rancher/k3s/*

    - name: Remove k3s install script
      ansible.builtin.file:
        path: /usr/local/bin/k3s-install.sh
        state: absent