---
- name: Configure agents
  hosts: agents
  become: true
  roles:
    - common
    - wireguard-client
  vars:
    ansible_python_interpreter: /usr/bin/python3      

- name: Configure management node
  hosts: management
  become: true
  roles:
    - common
    - wireguard-client
  vars:
    ansible_python_interpreter: /usr/bin/python3        

- name: Configure master (WireGuard)
  hosts: master
  become: true
  roles:
    - common
    - wireguard-server
  vars:
    ansible_python_interpreter: /usr/bin/python3        

- name: Configure master (K3s)
  hosts: master
  become: true
  roles:
    - k3s-server
  vars:
    ansible_python_interpreter: /usr/bin/python3          

- name: Configure agents (K3s)
  hosts: agents
  become: true
  roles:
    - k3s-agent
  vars:
    ansible_python_interpreter: /usr/bin/python3            

