
    #- name: Retrive already joined peers 
    # command : wg show wg0 endpoints
    #  register: peers


    - name: Append peer info in wg0.conf
      loop: "{{ groups['worker'] }}"
      #when: not (hostvars[item]['genkey_public_worker_' + item] in peers.stdout)
      lineinfile:
            path: "/etc/wireguard/wg0.conf"
            line: |
              [Peer]
              Endpoint = {{hostvars[item].ip_host}}:51820
              PublicKey = {{hostvars[item]['genkey_public_worker_' + item]}}
              AllowedIPs = {{hostvars[item]['ip_address_wireguard_' + item]}}/32
              PersistentKeepalive = 20
            insertafter: EOF
    - name: Activate Wireguard at boot
      command: "{{ item }}"
      loop:
        - systemctl enable wg-quick@wg0.service
        - systemctl daemon-reload       
     
    - name: Reload WireGuard 
      block:
          - command: wg-quick  {{ item }} wg0 
            with_items:
            - down
            - up
            failed_when: false
    - name: Reload WireGuard 
      block:
          - command: wg-quick  {{ item }} wg0 
            with_items:
            - down
            - up
            failed_when: false


