
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.l4responder_toolbox.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.l4responder_toolbox.rbac.clusterRole.name }}
rules:
{{- range .Values.l4responder_toolbox.rbac.clusterRole.rules }}
- apiGroups: {{ .apiGroups | toJson }}
  resources: {{ .resources | toJson }}
  verbs: {{ .verbs | toJson }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.l4responder_toolbox.rbac.clusterRoleBinding.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.l4responder_toolbox.rbac.clusterRole.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.l4responder_toolbox.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}