
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: toolbox
  namespace: {{.Values.global.namespace}}
  labels:
    app: toolbox
spec:
  selector:
    matchLabels:
      app: toolbox
  template:
    metadata:
      labels:
        app: toolbox
    spec:
      serviceAccountName: toolbox-sa
      hostNetwork: true
      containers:
        - name: toolbox
          image: {{  .Values.l4responder_toolbox.repository  }}
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName