apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volumes.pv.name }}
  labels:
    type: local
spec:
  storageClassName: {{ .Values.volumes.pv.storageClassName }}
  capacity:
    storage: {{ .Values.volumes.pv.capacity }}
  accessModes: {{ .Values.volumes.pv.accessModes }}
  hostPath:
    path: {{ .Values.volumes.pv.hostPath.path }}