global:
  namespace: clickhouse

clickhouse:
  image:
    repository: clickhouse/clickhouse-server
    tag: "24.8"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    httpPort: 8123
    nativePort: 9000

  node:
    hostname: master-00

  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"

  persistence:
    enabled: true
    hostPath: /data/clickhouse

  resources: {}