deploymentName: arp-responder
appName: arp-responder
namespace: ansible-managed
hostNetwork: true

containers:
  arp4:
    image: registry.local:30007/rvalentim/ipv4
    imagePullPolicy: IfNotPresent
    command:
      - "/usr/src/arpd/farpd2"
      - "-d"
      - "-i"
    args:
      - "eth0" # Use the variable
      - "10.10.0.0/24" # Use the variable
  arp6:
    image: registry.local:30007/rvalentim/ipv6
    imagePullPolicy: IfNotPresent
    command:
      - "/usr/src/arpv6/parasite6"
    args:
      - "eth0" # Use the variable

nodeAffinity:
  hostname:
    values:
      - poli-worker-00
