apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clickhouse.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "clickhouse.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: false
