---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "clickhouse.fullname" . }}-pv
  labels:
    app.kubernetes.io/name: {{ include "clickhouse.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    type: local
spec:
  storageClassName: {{ .Values.global.storageClass }}
  capacity:
    storage: {{ .Values.clickhouse.persistence.size }}
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.clickhouse.persistence.hostPath }}
    type: Directory
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "clickhouse.fullname" . }}-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "clickhouse.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.global.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.clickhouse.persistence.size }}
