#!/bin/bash

# Set the WireGuard IP address
WG_IP="10.0.0.1"

# Set the internet interface
iface="enp0s3"

# Install WireGuard
sudo apt-get install -y wireguard

# Generate WireGuard keys
wg genkey | tee privatekey | wg pubkey > publickey

# Create WireGuard configuration file
sudo bash -c "cat > /etc/wireguard/wg0.conf << EOF
[Interface]
 
# The IP address of this host in the wireguard tunnels
Address = $WG_IP
 
# Every Raspberry Pi connects via UDP to this port. Your Cloud VM must be reachable on this port via UDP from the internet.
ListenPort = 51820
 
# Set the private key to the value of the privatekey file generated by the previous command
PrivateKey = $(cat privatekey)

PostUp   = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o $iface -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o $iface -j MASQUERADE
EOF"

# Create WireGuard Up service file
sudo bash -c "cat > /etc/systemd/system/wireguard-up.service << EOF
[Unit]
Description=WireGuard Up Service
After=network.target

[Service]
Type=simpled
ExecStart=/usr/bin/wg-quick up wg0

[Install]
WantedBy=default.target
EOF"

# Reload systemd and start WireGuard service
sudo systemctl daemon-reload
sudo systemctl enable wireguard-up.service
sudo systemctl start wireguard-up.service

# Install K3s with WireGuard
curl -sfL https://get.k3s.io | K3S_NODE_NAME=master sh - 

# Check for an empty line and remove it before appending the echo message
sed -i '/^$/d' /etc/systemd/system/k3s.service

# Configure flannel in node
echo "ExecStart=/usr/local/bin/k3s server --advertise-address $WG_IP --flannel-iface=wg0" | sudo tee -a /etc/systemd/system/k3s.service

# Restart k3s service
sudo systemctl daemon-reload 
sudo systemctl restart k3s.service
