all:
  hosts:
    poli-master-00:
      ansible_host: vm1-bigdata.polito.it
      ansible_port: 22
      ansible_user: root
      # WireGuard server variables
      wireguard_ip: "10.0.0.100"
      public_interface: "ens2"
      wireguard_interface: "wg0"
      wireguard_private_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66363663316337643535666635613466303466623039376335333561643536613334306339626233
          6337613835623662323164303461316336363962633831630a366365386635376262396563313134
          35313534623965316664626630643239303963653862663034643531383265663038333035393539
          3362633363666464360a346435656638356664666561616131333562396639343762643064636265
          66626466383930383538633438613366313836326430646131386135326335636239636638613739
          3135643630386131303865616535366638633036613438663133
      wireguard_public_key: k6vJn2qKMJ4edWK0B5FBCF/cGWmYz76J5tNYnWzSLRk=
      wireguard_listen_port: "51820"
      wireguard_endpoint: "kubernetes.polito.it:51820"
      
    poli-worker-00:
      ansible_host: 90.147.183.9
      ansible_port: 2221
      ansible_host: "10.0.0.101"
      ansible_user: vagrant
      ansible_ssh_private_key_file: "~/.ssh/hiac/poli-worker-00"
      wireguard_ip: "10.0.0.101"
      public_interface: "eth0"
      wireguard_interface: "wg0"

    poli-worker-01:
      ansible_host: 90.147.183.9
      ansible_port: 2222
      ansible_host: "10.0.0.102"
      ansible_user: vagrant
      ansible_ssh_private_key_file: "~/.ssh/hiac/poli-worker-01"
      wireguard_ip: "10.0.0.102"
      public_interface: "eth0"
      wireguard_interface: "wg0"      

    garr-worker-00:
      ansible_host: 90.147.183.9
      ansible_port: 2223
      ansible_user: vagrant
      ansible_ssh_private_key_file: "~/.ssh/hiac/garr-worker-00"
      wireguard_ip: "10.0.0.103"
      public_interface: "eth0"
      wireguard_interface: "wg0"

    operator_drago:
      ansible_connection: local
      wireguard_ip: "10.0.0.2"
      public_interface: "eth0"
      wireguard_interface: "wg0"  

  children:
    deployment:
      hosts:
        localhost:
          ansible_connection: local
    registry:
      hosts:
        poli-master-00:
    master:
      hosts:
        poli-master-00:
    agents:
      hosts:
        poli-worker-00:
        poli-worker-01:
        garr-worker-00:
    management:
      hosts:
        operator_drago:
    vpn:
      hosts:
        poli-worker-00:
        poli-worker-01:
        garr-worker-00:
        operator_drago:

    darknet:
      hosts:
        poli-worker-00:
          darknet_range: "10.10.0.0/24"
          darknet_exclude_ips: 
            - 10.10.0.100
            - 10.10.0.101
            - 10.10.0.102
          hostPath: "/data/darknet"
          mountPath: "/data/darknet"
          tcpdump_interface: "eth0"
          tcpdump_rotate_seconds: "3600"
          tcpdump_file_pattern: "trace-%Y%m%d_%H-%M-%S_%s.pcap" 
        garr-worker-00:
          darknet_range: "10.10.0.0/24"
          darknet_exclude_ips: 
            - 10.10.0.100
            - 10.10.0.101
            - 10.10.0.102
          hostPath: "/data/darknet"
          mountPath: "/data/darknet"
          tcpdump_interface: "eth0"
          tcpdump_rotate_seconds: "3600"
          tcpdump_file_pattern: "trace-%Y%m%d_%H-%M-%S_%s.pcap" 
      vars: 
        namespace: "darknet"

    flower:
      hosts:
        # poli-master-00:
        # poli-worker-00:
      vars: 
        namespace: "arp-responder"
    
    cowrie:
      hosts:
        # poli-master-00:
        #   listening_ips:
        #     - 130.192.167.2
        #     - 130.192.167.3
        #   sshPort: 
        #     port: 2222
        #     targetPort: 2222
        #   telnetPort: 
        #     port: 2223
        #     targetPort: 2223
        #   hostPath: "/mnt/data/tcpdump"
        #   mountPath: "/etc/tcpdump"
        #   tcpdump_interface: "eth0"
        #   tcpdump_rotate_seconds: "3600"
        #   tcpdump_file_pattern: "trace-%Y%m%d_%H-%M-%S_%s.pcap"
      vars: 
        namespace: "cowrie"
    
    arp_responder:
      hosts:
        # poli-worker-1:
        #   arp4_interface: "eth1"
        #   arp4_network: "20.0.0.0/24"
        #   arp6_interface: "eth1"
        # poli-master-1:
        #   arp4_interface: "eth1"
        #   arp4_network: "20.0.0.0/24"
        #   arp6_interface: "eth1"
      vars: 
        namespace: "arp-responder"
  vars:
    # K3s variables
    helm_version: "v3.7.0"
    k3s_version: "v1.30.4+k3s1"
    k3s_url: "https://10.0.0.100:6443"
    deployed_applications: 
      - darknet
