all:
  hosts:
    master-00:
      ansible_host: <MASTER_IP>
      ansible_ssh_private_key_file: "<SSH_PRIVATE_KEY_PATH>"
      ansible_user: <USER>
      # WireGuard server variables
      wireguard_ip: "<WG_SERVER_IP>"
      public_interface: "<PUBLIC_INTERFACE>"
      wireguard_interface: "<WG_INTERFACE>"
      wireguard_private_key: !vault |
          <ENCRYPTED_VAULT_KEY>
      wireguard_public_key: <WG_PUBLIC_KEY>
      wireguard_listen_port: "<WG_LISTEN_PORT>"
      wireguard_endpoint: "<WG_ENDPOINT_IP>:<WG_LISTEN_PORT>"

    worker-00:
      ansible_host: <WORKER_00_IP>
      ansible_user: <USER>
      ansible_ssh_private_key_file: "<SSH_PRIVATE_KEY_PATH>"
      wireguard_ip: "<WG_WORKER_00_IP>"
      public_interface: "<PUBLIC_INTERFACE>"
      wireguard_interface: "<WG_INTERFACE>"

  children:
    deployment:
      hosts:
        localhost:
          ansible_connection: local
    registry:
      hosts:
        master-00:
    master:
      hosts:
        master-00:
    agents:
      hosts:
        worker-00:
    vpn:
      hosts:
        worker-00:
        
    darknet:
      hosts:
        worker-00:
          darknet_range: "<DARKNET_RANGE>"
          darknet_exclude_ips: 
            - <MASTER_IP>
            - <WORKER_00_IP>
            - <WORKER_01_IP>
          darknet_hostPath: "<DARKNET_HOST_PATH>"
          darknet_mountPath: "<DARKNET_MOUNT_PATH>"
          tcpdump_interface: "<TCPDUMP_INTERFACE>"
          tcpdump_rotate_seconds: "<TCPDUMP_ROTATE_SECONDS>"
          tcpdump_file_pattern: "<TCPDUMP_FILE_PATTERN>" 
      vars: 
        darknet_namespace: "<DARKNET_NAMESPACE>"
    cowrie:
      hosts:

        master-00:
          listening_ips:
            - <LISTENING_IP_1>
            - <LISTENING_IP_2>
          sshPort: 
            port: <SSH_PORT>
            targetPort: <SSH_TARGET_PORT>
          telnetPort: 
            port: <TELNET_PORT>
            targetPort: <TELNET_TARGET_PORT>
          hostPath: "<HOST_PATH>"
          mountPath: "<MOUNT_PATH>"
          tcpdump_interface: "<TCPDUMP_INTERFACE>"
          tcpdump_rotate_seconds: "<TCPDUMP_ROTATE_SECONDS>"
          tcpdump_file_pattern: "<TCPDUMP_FILE_PATTERN>"
      vars: 
        cowrie_namespace: "<COWRIE_NAMESPACE>"
    
    arp_responder:
      hosts:
        worker-1:
          arp4_interface: "<ARP4_INTERFACE>"
          arp4_network: "<ARP4_NETWORK>"
          arp6_interface: "<ARP6_INTERFACE>"
        master-1:
          arp4_interface: "<ARP4_INTERFACE>"
          arp4_network: "<ARP4_NETWORK>"
          arp6_interface: "<ARP6_INTERFACE>"
      vars: 
        arp_responder_namespace: "<ARP_RESPONDER_NAMESPACE>"
        
    flower_server:
      hosts:
        master-host:
          client_number: "<NUMBER_OF_EXPECTED_CLIENT>"
          round_number: "<NUMBER_OF_ROUND>"
          log_host_path: "<HOST_PATH_FOR_LOG>"
          vocabularies_host_path: "<HOST_PATH_FOR_VOCABULARIES>"
          models_host_path: "<HOST_PATH_FOR_MODELS>"
      vars: 
        flower_namespace: "flwr"

    flower_client:
      hosts:
        worker-host-01:
            cid: "<CLIENT-ID>"  #still required, but it can be removed in future release, UNIQUE
            log_host_path: "<HOST_PATH_FOR_LOG>"
            dataset_host_path: "<HOST_PATH_FOR_DATASET>"   #remember that the files with the data must be under /{dataset_host_path}/darknet0{cid}/ folder.
        worker-host-02:
            cid: "<CLIENT-ID>"  
            log_host_path: "<HOST_PATH_FOR_LOG>"
            dataset_host_path: "<HOST_PATH_FOR_DATASET>" 
      vars: 
        flower_namespace: "flwr"
  vars:
    # K3s variables
    helm_version: "<HELM_VERSION>"
    k3s_version: "<K3S_VERSION>"
    k3s_url: "<K3S_URL>"
    deployed_applications: 
      - darknet
      - arp_responder
      - flower-client
      - flower-server

