apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hpot-dionaea
  namespace: hpot
  labels:
    app.kubernetes.io/name: hpot-dionaea
spec:
  selector:
    matchLabels:
     app.kubernetes.io/name: hpot-dionaea
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hpot-dionaea
    spec:
      containers:
        - name: container-dionaea
          image: ghcr.io/telekom-security/dionaea:24.04 
        - name: container-netshoot
          image: nicolaka/netshoot      
          command: ["/bin/bash"]
          args: ["-c", "tcpdump -i any -G {{.Values.tcp_dump_parameters.G}}  -w {{ .Values.features.dionaea.folder_container }}/trace_dionaea_%Y%m%d_%H:%M:%S.pcap"]  # 86400 sec -> 1 day, file size 1 Gb
          volumeMounts:
          - mountPath: {{ .Values.features.dionaea.folder_container}}
            name: pv-storage-1
      volumes:
      - name: pv-storage-1
        persistentVolumeClaim:
          claimName: pvc-tcpdump-dionaea
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname 
                operator: In
                values:  
                      {{- range $v := .Values.features.dionaea.hosts }}
                      - {{ $v }}
                      {{- end }}

