- name: Uninstall Helm chart for Flower Server  on each agent node
  command: >
    helm uninstall flower-server-{{ item }} 
  environment:
    KUBECONFIG: "{{ fetch_result.dest }}"
  with_items: "{{ groups['flower_server'] }}"
