version: "3"

services:
  arp4:
    build: ./ipv4
    network_mode: "host"
    restart: always
    entrypoint: "/usr/src/arpd/farpd2"
    command: "-d -i eth0 10.0.0.0/24" 

  arp6:
    build: ./ipv6
    network_mode: "host"
    restart: always
    entrypoint: "/usr/src/arpv6/parasite6"
    command: "eth0" 
