version: '3'

services:
  pcap-collector:
    build:
      context: .
      dockerfile: Dockerfile
    image: pcap-collector:latest
    volumes:
      - ./ssh-key:/etc/ssh-keys:ro
      - ./data:/data/collector
    environment:
      - WORKER_NODES=worker-00 worker-01
      - SOURCE_PATH=/data/darknet
      - SSH_USER=vagrant
      - COLLECTION_INTERVAL=3600
    restart: unless-stopped