- name: Deploy Helm chart for Darknet TCPDump in each required node
  command: >
    {% set used_listening_ips = hostvars[item].darknet_exclude_ips | default([]) %}
    {% set server_ip = [] %}
    {% for ip in used_listening_ips %}
      {% set _ = server_ip.append("host " + ip) %}
    {% endfor %}
    {% set filter_condition = "ip and (net " ~ hostvars[item].darknet_range ~ ")" %}
    {% if server_ip %}
      {% set filter_condition = filter_condition ~ " and not (" ~ server_ip | join(' or ') ~ ")" %}
    {% endif %}

    helm upgrade -i darknet-ansible-{{ item }} {{ playbook_dir }}/resources/helm-charts/darknet --namespace {{ hostvars[item].darknet_namespace }} --create-namespace
    --set name=darknet-{{ item }}
    --set appName=darknet-{{ item }}
    --set namespace={{ hostvars[item].darknet_namespace }}
    --set volumes.pv.name=darknet-pv-{{ item }}
    --set volumes.pvc.name=darknet-pvc-{{ item }}
    --set containers.tcpdump.interface="{{ hostvars[item].tcpdump_interface }}"
    --set containers.tcpdump.filter="{{ filter_condition }}"
    --set containers.tcpdump.rotate_seconds="{{ hostvars[item].tcpdump_rotate_seconds }}"
    --set containers.tcpdump.outputPath="{{hostvars[item].darknet_mountPath}}/{{ hostvars[item].tcpdump_file_pattern }}"
    --set containers.tcpdump.mountPath="{{hostvars[item].darknet_mountPath}}"
    --set volumes.pvc.hostPath.path="{{ hostvars[item].darknet_hostPath }}"       
    --set nodeAffinity.hostname.values[0]="{{ item }}"
  environment:
    KUBECONFIG: "{{ fetch_result.dest }}"
  with_items: "{{ groups['darknet'] }}"