deploymentName: cowrie
appName: cowrie
namespace: ansible-managed
hostNetwork: true

containers:
  cowrie:
    image: cowrie/cowrie:latest
    imagePullPolicy: IfNotPresent
  tcpdump:
    image: nicolaka/netshoot
    imagePullPolicy: IfNotPresent
    monthPath: /etc/tcpdump
    command:
      - "/bin/bash"
      - "-c"
    interface: eth0
    rotate_seconds: 3600
    filter: "ip and (net 10.10.0.0/24)"
    outputPath: "/etc/tcpdump/trace-%Y%m%d_%H-%M-%S_%s.pcap"

nodeAffinity:
  hostname:
    values:
      - poli-worker-00

volumes:
  pv:
    name: pv-volume-tcpdump-cowrie
    storageClassName: manual
    capacity: 5Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: "/mnt/data/tcpdump"
  pvc:
    name: pvc-tcpdump-cowrie
    storageClassName: manual
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi

service:
  ports:
    sshPort:
      name: ssh-port
      protocol: TCP
      port: 2222
      targetPort: 2222
    telnetPort:
      name: telnet-port
      protocol: TCP
      port: 2223
      targetPort: 2223
  externalIPs:
    - 198.51.100.32
    - 198.51.100.33
