- name: Deploy Helm chart for Cowrie with TCPDump in each required node
  command: >
    {% set host_config = host_specific[item] | default({}) %}
    {% set listening_ips = host_config.listening_ips | default([]) %}
    {% set sshPort = host_config.sshPort | default({}) %}
    {% set telnetPort = host_config.telnetPort | default({}) %}
    {% set hostPath = host_config.hostPath | default('') %}
    {% set mountPath = host_config.mountPath | default('') %}
    {% set tcpdump_rotate_seconds = host_config.tcpdump_rotate_seconds | default(tcpdump_rotate_seconds) %}
    {% set tcpdump_file_pattern = host_config.tcpdump_file_pattern | default(tcpdump_file_pattern) %}
    {% set filter_ips = [] %}
    {% for ip in listening_ips %}
      {% set _ = filter_ips.append("host " + ip) %}
    {% endfor %}

    helm upgrade -i cowrie-ansible-{{ item }} {{ playbook_dir }}/resources/helm-charts/cowrie --namespace {{ namespace }} --create-namespace
    --set name=cowrie-{{ item }}
    --set appName=cowrie-{{ item }}
    --set namespace={{ namespace }}
    --set volumes.pv.name=cowrie-pv-{{ item }}
    --set volumes.pvc.name=cowrie-pvc-{{ item }}
    --set containers.tcpdump.filter="(port {{ sshPort.port }} or port {{ telnetPort.port }}) and ({{ filter_ips | join(' or ') }})"
    --set containers.tcpdump.rotate_seconds="{{ tcpdump_rotate_seconds }}"
    --set containers.tcpdump.outputPath="{{ mountPath }}/{{ tcpdump_file_pattern }}"
    --set containers.tcpdump.mountPath="{{ mountPath }}"
    --set volumes.pvc.hostPath.path="{{ hostPath }}"
    --set nodeAffinity.hostname.values[0]="{{ item }}"
  environment:
    KUBECONFIG: "{{ fetch_result.dest }}"
  with_items: "{{ groups['cowrie'] }}"
  when: host_specific[item] is defined