# Disable parallel execution
ENV['VAGRANT_NO_PARALLEL'] = 'yes'

# Define a Node class to encapsulate node properties
class Node
  attr_reader :role, :box, :mac

  def initialize(role, box, mac)
    @role = role
    @box = box
    @mac = mac
  end
end

# Define the nodes
NODES = [
  Node.new("poli-master-00", "generic/ubuntu2204", "00:00:00:00:00:AA"),
  Node.new("poli-worker-00", "generic/ubuntu2204", "00:00:00:00:00:BB"),
  Node.new("garr-worker-00", "generic/ubuntu2204", "00:00:00:00:00:CC")
]

# Common configuration
NODE_CPUS = 2
NODE_MEMORY = 2048

Vagrant.configure("2") do |config|
  # Default provider is libvirt, virtualbox is only provided as a backup
  config.vm.provider "libvirt" do |v|
    v.cpus = NODE_CPUS
    v.memory = NODE_MEMORY
    v.mgmt_attach = false
  end

  config.vm.provider "virtualbox" do |v|
    v.cpus = NODE_CPUS
    v.memory = NODE_MEMORY
    v.linked_clone = true
    v.customize [
      "modifyvm", :id,
      "--paravirtprovider", "minimal",
      "--cpus", "2",
      "--cableconnected1", "on"
    ]
  end

  NODES.each do |node|
    config.vm.define node.role do |n|
      n.vm.box = node.box
      n.vm.hostname = node.role
      n.vm.network "private_network", mac: node.mac, libvirt__network_name: "honeynet"

      # Use a provisioning script to set up basic configuration
      n.vm.provision "ansible" do |ansible|
        ansible.playbook = "basicsetup.yml"
        ansible.compatibility_mode = "2.0"
      end
    end
  end
end
