ENV['VAGRANT_NO_PARALLEL'] = 'yes'
NODE_ROLES = ["poli-master-00", "poli-worker-00", "garr-worker-00"]
NODE_BOXES = ['generic/ubuntu2204', 'generic/ubuntu2204', 'generic/ubuntu2204']
NODE_CPUS = 2
NODE_MEMORY = 2048
NODE_MACS = ["00:00:00:00:00:AA", "00:00:00:00:00:BB", "00:00:00:00:00:CC"] 

def provision(vm, role, node_num)
  vm.box = NODE_BOXES[node_num]
  vm.hostname = role 
  vm.network "private_network", mac: NODE_MACS[node_num], libvirt__network_name: "honeynet"
  
  # Use a provisioning script to set up basic configuration
  vm.provision "ansible" do |ansible|
    ansible.playbook = "basicsetup.yml"
    ansible.compatibility_mode = "2.0"
  end
end

Vagrant.configure("2") do |config|
  # Default provider is libvirt, virtualbox is only provided as a backup
  config.vm.provider "libvirt" do |v|
    v.cpus = NODE_CPUS
    v.memory = NODE_MEMORY
    v.mgmt_attach = false
  end
  config.vm.provider "virtualbox" do |v|
    v.cpus = NODE_CPUS
    v.memory = NODE_MEMORY
    v.linked_clone = true
    v.customize [
      "modifyvm", :id,
      "--paravirtprovider", "minimal",
      "--cpus", "2",
      "--cableconnected1", "on"
    ]
  end
  
  NODE_ROLES.each_with_index do |name, i|
    config.vm.define name do |node|
      node.vm.box = NODE_BOXES[i]
      node.vm.hostname = name
      provision(node.vm, name, i)
    end
  end
end
