ENV['VAGRANT_NO_PARALLEL'] = 'yes'
NODE_ROLES = ["polito-master-0", "polito-worker-0", "garr-worker-0"]
NODE_BOXES = ['generic/ubuntu2204', 'generic/ubuntu2204', 'generic/ubuntu2204']
NODE_CPUS = 2
NODE_MEMORY = 2048
NETWORK_PREFIX = "10.10.10"
NODE_MACS = ["08:00:27:00:00:01", "08:00:27:00:00:02", "08:00:27:00:00:03"] 

def provision(vm, role, node_num)
  vm.box = NODE_BOXES[node_num]
  vm.hostname = role
  
  node_ip = "#{NETWORK_PREFIX}.#{100+node_num}"
  vm.network "private_network", ip: node_ip, netmask: "255.255.255.0", mac: NODE_MACS[node_num]
  
  # Use a provisioning script to set up basic configuration
  vm.provision "ansible" do |ansible|
    ansible.playbook = "basicsetup.yml"
    ansible.compatibility_mode = "2.0"
  end
end

Vagrant.configure("2") do |config|
  # Default provider is libvirt, virtualbox is only provided as a backup
  config.vm.provider "libvirt" do |v|
    v.cpus = NODE_CPUS
    v.memory = NODE_MEMORY
    v.mgmt_attach = false
  end
  config.vm.provider "virtualbox" do |v|
    v.cpus = NODE_CPUS
    v.memory = NODE_MEMORY
    v.linked_clone = true
    v.customize [
      "modifyvm", :id,
      "--paravirtprovider", "minimal",
      "--cpus", "2",
      "--cableconnected1", "on"
    ]
  end
  
  NODE_ROLES.each_with_index do |name, i|
    config.vm.define name do |node|
      node.vm.box = NODE_BOXES[i]
      node.vm.hostname = name
      provision(node.vm, name, i)
    end
  end
end
