apiVersion: v1
name: registry
description: A Helm chart for a private docker registry.
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - registry
maintainers:
  - name: Rodolfo Valentim
    email: rodolfo.vieira@polito.it
dependencies: []

# helm install my-release ./my-chart --namespace my-namespace --create-namespace -f values.yaml
