---
- name: Update apt cache and install dependencies
  ansible.builtin.apt:
    update_cache: yes
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: Remove existing Docker installations
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Ensure required variables are set
  ansible.builtin.set_fact:
    os_name: "{{ ansible_distribution | default('debian') | lower }}"
    os_release: "{{ ansible_distribution_release | default('bookworm') }}"

- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ os_name }}/gpg"
    state: present

- name: Determine repository
  ansible.builtin.set_fact:
    docker_repo: >-
      deb https://download.docker.com/linux/{{ os_name }} {{ os_release }} stable

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_repo }}"
    state: present
    filename: docker
    update_cache: yes

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Create Docker daemon configuration directory
  file:
    path: /etc/docker
    state: directory
    mode: '0755'

- name: Configure Docker daemon options
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "insecure-registries" : ["{{ local_registry }}""]
      }
    mode: '0644'

- name: Ensure Docker service is started and enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
    
- name: Download Helm command line tool
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0700'

- name: Install Helm
  ansible.builtin.command:
    cmd: /tmp/get_helm.sh
    creates: /usr/local/bin/helm
  environment:
    DESIRED_VERSION: "{{ helm_version | default('') }}"

- name: Remove Helm installer script
  ansible.builtin.file:
    path: /tmp/get_helm.sh
    state: absent