---
- name: Create rsync script for each host in darknet group
  template:
    src: rsync_script.sh.j2
    dest: /home/{{ ansible_user }}/rsync_script-{{ item }}.sh
    mode: '0755'  # Make the script executable
  with_items: "{{ groups['darknet'] }}"
  vars:
    host_config: "{{ host_specific[item] | default({}) }}"
    darknet_hostPath: "{{ host_config.darknet_hostPath | default(darknet_hostPath) }}"
    
- name: Create cron job to run the rsync script for each host in darknet group
  cron:
    name: "Run rsync script for {{ item }}"
    minute: "*/1"  # Set the cron to run every minute
    job: "/home/{{ ansible_user }}/rsync_script-{{ item }}.sh"
    state: present
  with_items: "{{ groups['darknet'] }}"
  when: host_specific[item] is defined