apiVersion: apps/v1
kind: Deployment
metadata:
  name: arp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arp-app
  template:
    metadata:
      labels:
        app: arp-app
    spec:
      hostNetwork: true
      containers:
        - name: arp4
          image: your-namespace/ipv4:latest # Replace with your image registry and tag
          command: ["/usr/src/arpd/farpd2"]
          args: ["-d", "-i", "eth0", "10.0.0.0/24"]
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          restartPolicy: Always
        - name: arp6
          image: your-namespace/ipv6:latest # Replace with your image registry and tag
          command: ["/usr/src/arpv6/parasite6"]
          args: ["eth0"]
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          restartPolicy: Always
