#infrastructure/ansible/inventory/dev/group_vars/all.yml
---
helm_version: "v3.18.3"
k3s_version: "v1.33.1+k3s1"
k3s_url: "https://127.0.0.1:6443"

# Project paths - using playbook_dir as base since that's where ansible runs from
project_root: "{{ playbook_dir }}/../../../"

# Docker registry configuration
local_registry: "registry.local:5000"
image_tag: "latest"
  
