---
# Development clickhouse Application Configuration

namespace: clickhouse
chart_path: "{{ playbook_dir }}/../../../applications/clickhouse/helm"

values:
  clickhouse:
    node:
      hostname: master-00
    database: "holoscope"
    user: "holoscope"
    password: "dev-holoscope-changeme"