---
# Development Darknet Application Configuration
enabled: true
namespace: darknet
chart_path: "{{ playbook_dir }}/../../../applications/darknet/helm"

# Docker images to build
docker_images:
  - name: "ipv4"
    author: "public" 
    path: "applications/darknet/docker/ipv4"
    dockerfile: "Dockerfile"
    tag: "latest"
 

# Helm chart values
values:
  # Node configurations
  darknetNodes:
    worker-01:
      enabled: true
      config:
        addresses: 
        - address: 10.0.0.99/30
      arp:
        enabled: false
