---
# Development l4responder Application Configuration
enabled: true
namespace: l4responder
chart_path: "{{ playbook_dir }}/../../../applications/l4responder/helm"
docker_images:
  - name: "l4responder_server"
    author: "public"
    path: "applications/l4responder/docker/l4responder_server"
    dockerfile: "Dockerfile"
    tag: "latest"

values:
  l4responder_server:
    enabled: true
    workers:
      worker-00:
          enabled: true
      worker-01:
          enabled: false
