---
- name: Install K3s server
  shell: |
          curl -sfL https://get.k3s.io | K3S_NODE_NAME="{{inventory_hostname}}" INSTALL_K3S_VERSION="{{ k3s_version }}" K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="server" sh -s -  --advertise-address="{{hostvars[ inventory_hostname ].wireguard_ip}}"  --flannel-iface=wg0 --debug --docker

- name: Remove need of sudo for kubectl
  command: chmod 644 /etc/rancher/k3s/k3s.yaml

