apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.pvc.name }}
spec:
  storageClassName: {{ .Values.volumes.pvc.storageClassName }}
  accessModes: {{ .Values.volumes.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.volumes.pvc.resources.requests.storage }}
