apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.appName }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      containers:
        - name: arp4-responder
          image: {{ .Values.containers.arp4.image }}
          imagePullPolicy: {{ .Values.containers.arp4.imagePullPolicy }}
          command: {{ .Values.containers.arp4.command | toJson}}
          args: {{ .Values.containers.arp4.args | toJson }}
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
        - name: arp6-responder
          image: {{ .Values.containers.arp6.image }}
          imagePullPolicy: {{ .Values.containers.arp6.imagePullPolicy }}
          command: {{ .Values.containers.arp6.command | toJson }}
          args: {{ .Values.containers.arp6.args | toJson }}
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values: 
                    {{- range .Values.nodeAffinity.hostname.values }}
                    - {{ . }}
                    {{- end }}

