# inventory/group_vars/arp.yml
---
# ARP application settings
arp_namespace: "arp"
enabled: false

arp_images:
  - name: ipv4
    path: "resources/docker-images/arp/ipv4/"
    author: "public"
  - name: ipv6
    path: "resources/docker-images/arp/ipv6/"
    author: "public"

# Host-specific configurations
host_specific:
  worker-00:
    arp4_interface: "eth0"
    arp4_network:   "10.128.0.0/24"
    arp6_interface: "eth0"
    arp6_network:   "2001:db8:0:0::/64"
    
  worker-01:
    arp4_interface: "eth0"
    arp4_network:   "10.129.0.0/24"
    arp6_interface: "eth0"
    arp6_network:   "2001:db8:0:1::/64"
