# inventory/group_vars/arp_responder.yml
---
# ARP responder application settings
arp_responder_namespace: "arp-responder"
enabled: true

# Host-specific configurations
host_specific:
  worker-00:
    arp4_interface: "eth0"
    arp4_network:   "10.128.128.0/24"
    arp6_interface: "eth0"
    arp6_network:   "2001:db8:0:0::/64"
    
  worker-01:
    arp4_interface: "eth0"
    arp4_network:   "10.128.129.0/24"
    arp6_interface: "eth0"
    arp6_network:   "2001:db8:0:1::/64"
