---
# Collector application settings
collector_namespace: "darknet"
collector_dstPath: "/data/collector"
collector_srcPath: "/data/darknet"
collector_interval: "120"  

collector_images:
  - name: collector
    path: "resources/docker-images/collector/"
    author: "public"
  

# Deployment settings
enabled: true