global:
  namespace: toolbox
  storageClass: manual

# Image tag — overridden at deploy time with git SHA
image_tag: latest

toolbox:
  name: toolbox
  labels:
     app: toolbox
  container:
    name: toolbox
    image:
      repository: registry.local:5000/public/toolbox
      pullPolicy: IfNotPresent
  serviceAccount:
    name: toolbox-sa
  securityContext:
    privileged: false
    capabilities:
      add: ["NET_ADMIN", "NET_RAW"]
      drop: ["ALL"]
  network:
    hostNetwork: true
  
  
  rbac:
    clusterRole:
      name: pod-reader
      rules:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["get", "list", "watch"]
          
    clusterRoleBinding:
        name: toolbox-sa-binding